services:
  model_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: be_service
    hostname: be_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=plane_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
